name: Android CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./cheat
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: always()
      with:
        # Artifact name
        name: Build Result
        # Directory containing files to upload
        path: ./cheat/app/build/
    - name: Upload APK artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: APK
        # Directory containing files to upload
        path: ./cheat/app/build/outputs/apk/debug/app-debug.apk